### ISSUE TITLE
Add functionality to use GNINA pre-trained models

### ISSUE THREAD

**Issue by RMeli** [RMeli/gnina-torch#35]
Weights of the pre-trained GNINA models were provided in #34 by @drewnutt , getting a steps closer towards #33 .

The following needs to be implemented in order to have the weights readily available:
- [x] Automatic loading weights into the current models
     - [x] `default2017` #36
     - [x] `default2018` #36
     - [x] `dense` #44 
- [x] Support ensemble of models  #38 
    - [x] Support GNINA `default` model #44 
- [x] Publish package on PyPI and conda-forge
    - [x] Change name to `gninatorch` #37 
 
This additional functionality could be implemented in `gnina.py` and follow the GNINA command line as closely as possible. In addition to `.types` files, it would be good to use `molgrid.openbabel` to provide the `--receptor` and `--ligand` options.
